language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./Frontend/
  - dotnet build ./IdentityServer/
  - dotnet build ./AdminSite/
  - dotnet test ./Tests/
  - cd Frontend/ClientApp && npm test
