language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet restore
  - dotnet build ./src/Frontend/
  - dotnet build ./src/IdentityServer/
  - dotnet build ./src/AdminSite/
  - dotnet test  ./Tests/
  - cd src/Frontend/ClientApp && npm test
