language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./src/Frontend/
  - dotnet build ./src/IdentityServer/
  - dotnet build ./src/AdminSite/
  - dotnet test  ./src/Tests/
  - cd src/Frontend/ClientApp && npm test
