version: '3'

services:
  musicstore-sharedlibs:
    image: musicstore-sharedlibs
    build: 
      context: ./Shared
  frontend-site:
    image: musicstore-frontend
    build: 
      context: ./Frontend
    ports:
      - 5600:80
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
  oauthapp:
    image: musicstore-oauthapp
    build: 
      context: ./samples/oauthtest
    ports:
      - 5607:80
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
  identityserver:
    image: musicstore-identityserver
    build: 
      context: ./IdentityServer
    ports:
      - 5601:80
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
  adminsite:
    image: musicstore-adminsite
    build: 
      context: ./AdminSite
    ports:
      - 5604:80
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
  db-seeder:
    image: musicstore-db-seeder
    build: 
      context: ./DatabaseSeeder
    depends_on:
      - musicstore-sharedlibs
      - db
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      AngularAppClientUrl: http://localhost:5600
      MvcAppClientUrl: http://localhost:5607
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"