version: '3'

services:
  musicstore-sharedlibs:
    image: musicstore-sharedlibs
    build: 
      context: ./src/Shared
  frontend-site:
    image: musicstore-frontend
    build: 
      context: ./src/Frontend
    ports:
      - 8050:80
      - 44350:443
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORT: 44350
  oauthapp:
    image: musicstore-oauthapp
    build: 
      context: ./src/samples/oauthtest
    ports:
      - 8057:80
      - 44357:443
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORT: 44357
  identityserver:
    image: musicstore-identityserver
    build: 
      context: ./src/IdentityServer
    ports:
      - 8053:80
      - 44353:443
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORT: 44353
  adminsite:
    image: musicstore-adminsite
    build: 
      context: ./src/AdminSite
    ports:
      - 8054:80
      - 44354:443
    depends_on:
      - musicstore-sharedlibs
      - db
      - db-seeder
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTPS_PORT: 44354
  db-seeder:
    image: musicstore-db-seeder
    build: 
      context: ./src/DatabaseSeeder
    depends_on:
      - musicstore-sharedlibs
      - db
    environment:
      ConnectionStrings:SqlServerConnection: ${DOCKER_CONNECTIONSTRING}
      ASPNETCORE_ENVIRONMENT: localdocker
      AngularAppClientUrl: https://localhost:44350
      MvcAppClientUrl: https://localhost:44357
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"